language: php
php:
  - 5.4
  - 5.5
services:
  - mysql
before_script:
  - make diagnose
  - php composer.phar install
  - mysql -e 'create database uonline_test;'
  - echo "localhost|travis||uonline_test|travis|off" > keyring
  - php init.php --tables --unify-validate --unify-export --test-monsters --optimize
script:
  - make test
