language: php
php:
  - "5.5"
  - "5.4"
services:
  - mysql
  - postgresql
env:
  - MYSQL_DATABASE_URL=mysql://travis:@localhost/uonline
before_script:
  - # Node.js setup
  - sudo apt-get update
  - sudo apt-get install nodejs
  - node --version
  - npm install
  - # PHP setup
  - make diagnose
  - ./composer.phar install
  - # Database setup
  - echo "localhost|travis||uonline|off" > keyring
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize --drop  # test full cycle
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize
  - ./init.php --info
script:
  - make checkstrict
  - make checklicense
  - make lint
  - make test
