language: node_js
node_js:
  - "0.12"
  - "stable"
addons:
  postgresql: "9.3"
  # <DIRTY HACK>
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  # </DIRTY HACK>
env:
  - CXX=g++-4.8 DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test"
  # ^^^^^^^^^^^ DIRTY HACK
before_script:
  - # test scripts
  - ./init.coffee --info || true
  - ./init.coffee --create-database both --migrate-tables --unify-export --monsters --optimize-tables
  - ./init.coffee --info
  - ./add-admin.coffee admin password
  - ./init.coffee --drop-database both
  - ./init.coffee --info || true
  - # Create test database
  - psql -c 'create database uonline_test;' -U postgres
script:
  - gulp build
  - grunt travis
# New stack
sudo: false
cache:
  directories:
  - node_modules
