language: php
php:
  - 5.4
  - 5.5
services:
  - mysql
before_script:
  - make diagnose
  - php composer.phar install
  - echo "localhost|travis||uonline|off" > keyring
  - php init.php --info
  - php init.php --database --tables --unify-validate --unify-export --test-monsters --optimize --drop  # test full cycle
  - php init.php --database --tables --unify-validate --unify-export --test-monsters --optimize
script:
  - make testl
