language: node_js
node_js:
  - "0.10"
services:
  - mysql
  - postgresql
env:
  - DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test" MYSQL_DATABASE_URL="mysql://travis:@localhost/uonline" MYSQL_DATABASE_URL_TEST="mysql://travis:@localhost/uonline_test"
before_script:
  - # init.coffee test
  - ./init.coffee --info || true
  - ./init.coffee --create-database both --migrate-tables --optimize-tables --test-monsters
  - ./init.coffee --info
  - ./add-admin.coffee admin password
  - ./init.coffee --drop-database both
  - ./init.coffee --info || true
  - # Create test database
  - mysql -e 'create database uonline_test;'
script:
  - grunt
after_script:
  - ./node_modules/nodeunit/bin/nodeunit tests_node/ --reporter lcov | travis_retry ./node_modules/coveralls/bin/coveralls.js
