language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mysql
  - postgresql
before_script:
  - # PHP setup
  - sudo apt-get install php
  - make diagnose
  - ./composer.phar install
  - # Node.js setup
  - npm install
  - # Database setup
  - echo "localhost|travis||uonline|off" > keyring
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize --drop  # test full cycle
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize
  - ./init.php --info
script:
  - make testl
